export const Skill = [
  { name: "html5", image: "/html-5.svg" },
  { name: "css", image: "/css.svg" },
  { name: "js", image: "/javascript.svg" },
  { name: "python", image: "/python.svg" },
  { name: "php", image: "/php.svg" },
  { name: "mysql", image: "/mysql.svg" },
  { name: "mongodb", image: "/mongodb.svg" },
  { name: "nodejs", image: "/nodejs.svg" },
  { name: "boostrap", image: "/bootstrap.svg" },
  { name: "materialui", image: "/materialui.svg" },
  { name: "tailwindcss", image: "/tailwindcss.svg" },
  { name: "expressjs", image: "/expressjs.svg" },
  { name: "react cycle", image: "/react.svg" },
  { name: "next", image: "/nextjs.svg" },
  { name: "django", image: "/django.svg" },
  { name: "laravel", image: "/laravel.svg" },
  { name: "linux", image: "/linux.svg" },
  { name: "alighmotion", image: "/alightmotion.svg" },
  { name: "figma", image: "/figma.svg" },
  { name: "photoshop", image: "/photoshop.svg" },
];
